---
# code: language=ansible
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json
- name: Execute post create task
  hosts: all
  become: false
  gather_facts: false
  connection: local
  pre_tasks:
    - name: マシン情報を取得
      ansible.builtin.setup:
        gather_subset:
          - system
      become: true
      tags: always
  roles:
    - role: lde
      when: ansible_facts.system == 'Linux'
      tags: role_lde
    - role: font
      become: true
      tags: role_font
      when: ansible_facts.system == "Linux"
    - role: redmine
      tags: role_redmine
      when: ansible_facts.system == "Linux"
    - role: document
      when: ansible_facts.system == "Linux"
      tags: role_document
    - role: vscode
      when: ansible_facts.system == "Linux"
      tags: role_vscode
  tasks:
    - name: VSCodeのタスクを元にtaskのタスクに変換
      ansible.builtin.set_fact:
        task_tasks: "{{ task_tasks | default({}) | combine((task_task | items2dict)) }}"
      vars:
        task_task:
          - key: "{{ item.label | lower | regex_replace('( |:)', '_') }}"
            value:
              cmds:
                - "{{ item.command }}"
      loop: "{{ vscode_tasks }}"
      loop_control:
        label: "{{ item.label }}"
    - name: taskの設定ファイルを生成/更新
      ansible.builtin.blockinfile:
        path: "{{ base_dir }}/Taskfile.yml"
        content: "{{ task_config | to_nice_yaml }}"
        mode: "0644"
        create: true
      vars:
        task_config:
          version: 3
          tasks: "{{ task_tasks }}"
