---
# code: language=ansible
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json
- name: Execute post start task
  hosts: all
  become: false
  gather_facts: false
  connection: local
  tasks:
    - name: 環境変数の有効化
      ansible.builtin.command:
        cmd: direnv allow
        removes: "{{ playbook_dir | dirname }}/.envrc"
        chdir: "{{ playbook_dir | dirname }}"
