---
- name: Set Install version variable
  when: lde_d2_version | default('latest') == 'latest'
  block:
    - name: Get latest version
      ansible.builtin.import_tasks:
        file: common/get_latest_version.yml
      vars:
        github_repo: terrastruct/d2
    - name: Set version variable
      ansible.builtin.set_fact:
        lde_d2_version: "{{ latest_version }}"
- name: Set architecture variable
  ansible.builtin.set_fact:
    d2_arch: "{{ d2_arch_types[ansible_facts['architecture']] }}"
  vars:
    d2_arch_types:
      x86_64: amd64
      aarch64: arm64
- name: d2のインストール
  become: true
  block:
    - name: Create download directory
      ansible.builtin.file:
        path: /usr/local/src/d2
        state: directory
        mode: "0755"
    - name: Download d2
      ansible.builtin.unarchive:
        src: https://github.com/terrastruct/d2/releases/download/{{ lde_d2_version }}/d2-{{ lde_d2_version }}-linux-{{ d2_arch }}.tar.gz
        dest: /usr/local/src/d2
        extra_opts:
          - --strip-components=1
        remote_src: true
      register: d2_unarchive_result
    - name: Install/update d2
      ansible.builtin.command:
        cmd: /usr/local/src/d2/scripts/install.sh
        chdir: /usr/local/src/d2
      when: d2_unarchive_result is changed
