---
- name: 現在のワークスペースを安全なディレクトリとして設定する
  community.general.git_config:
    name: safe.directory
    value: "{{ playbook_dir | dirname }}"
    scope: global
- name: Git管理下から除外するファイルの設定を追加
  ansible.builtin.blockinfile:
    path: "{{ base_dir }}/.gitignore"
    content: "{{ lde_git_append_gitignore }}"
  register: gitignore_result
- name: git管理下のファイルの変更を無視するように設定
  ansible.builtin.command:
    cmd: git update-index --assume-unchanged {{ item }}
    chdir: "{{ base_dir }}"
  loop: "{{ git_assume_unchanged_files | default(['.gitignore']) }}"
