- name: yarn/pnpm/niのインストール
  become: true
  block:
    - name: yarnのインストール/更新
      community.general.npm:
        name: yarn
        global: true
        state: latest
    - name: pnpmのインストール/更新
      community.general.npm:
        name: pnpm
        global: true
        state: latest
    - name: niのインストール/更新
      community.general.npm:
        name: "@antfu/ni"
        global: true
        state: latest
