---
- name: Set Install version variable
  when: lde_pandoc_version | default('latest') == 'latest'
  block:
    - name: Get latest version
      ansible.builtin.import_tasks:
        file: common/get_latest_version.yml
      vars:
        github_repo: jgm/pandoc
    - name: Set version variable
      ansible.builtin.set_fact:
        lde_pandoc_version: "{{ latest_version }}"
- name: Set architecture variable
  ansible.builtin.set_fact:
    pandoc_arch: "{{ pandoc_arch_types[ansible_facts['architecture']] }}"
  vars:
    pandoc_arch_types:
      x86_64: amd64
      aarch64: arm64
- name: Install pandoc
  ansible.builtin.apt:
    deb: https://github.com/jgm/pandoc/releases/download/{{ lde_pandoc_version }}/pandoc-{{ lde_pandoc_version }}-1-{{ pandoc_arch }}.deb
  become: true
