---
- name: Set Install version variable
  when: lde_runn_version | default('latest') == 'latest'
  block:
    - name: Get latest version
      ansible.builtin.import_tasks:
        file: common/get_latest_version.yml
      vars:
        github_repo: k1LoW/runn
    - name: Set version variable
      ansible.builtin.set_fact:
        lde_runn_version: "{{ latest_version }}"
- name: Set architecture variable
  ansible.builtin.set_fact:
    runn_arch: "{{ runn_arch_types[ansible_facts['architecture']] }}"
  vars:
    runn_arch_types:
      x86_64: amd64
      aarch64: arm64
- name: Install tbls
  ansible.builtin.apt:
    deb: https://github.com/k1LoW/runn/releases/download/{{ lde_runn_version }}/runn_{{ lde_runn_version[1:] }}-1_{{ runn_arch }}.deb
  become: true
