---
- name: Set Install version variable
  when: lde_task_version | default('latest') == 'latest'
  block:
    - name: Get latest version
      ansible.builtin.import_tasks:
        file: common/get_latest_version.yml
      vars:
        github_repo: go-task/task
    - name: Set version variable
      ansible.builtin.set_fact:
        lde_task_version: "{{ latest_version }}"
- name: Set architecture variable
  ansible.builtin.set_fact:
    task_arch: "{{ task_arch_types[ansible_facts['architecture']] }}"
  vars:
    task_arch_types:
      x86_64: amd64
      aarch64: arm64
- name: Install task
  ansible.builtin.apt:
    deb: https://github.com/go-task/task/releases/download/{{ lde_task_version }}/task_{{ ansible_facts['system'] | lower }}_{{ task_arch }}.deb
  become: true
