---
- name: Set Install version variable
  when: lde_tbls_version | default('latest') == 'latest'
  block:
    - name: Get latest version
      ansible.builtin.import_tasks:
        file: common/get_latest_version.yml
      vars:
        github_repo: k1LoW/tbls
    - name: Set version variable
      ansible.builtin.set_fact:
        lde_tbls_version: "{{ latest_version }}"
- name: Set architecture variable
  ansible.builtin.set_fact:
    tbls_arch: "{{ tbls_arch_types[ansible_facts['architecture']] }}"
  vars:
    tbls_arch_types:
      x86_64: amd64
      aarch64: arm64
- name: Install tbls
  ansible.builtin.apt:
    deb: https://github.com/k1LoW/tbls/releases/download/{{ lde_tbls_version }}/tbls_{{ lde_tbls_version[1:] }}-1_{{ tbls_arch }}.deb
  become: true
